name: Deploy Frontend to HF Gradio Space

on:
  push:
    branches: [ main ]
    paths:
      - frontend/**

env:
  HF_SPACE_NAME: nlp-semantic-search-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Clone HF backend Space (authenticated)
        run: |
          git clone https://Alex-Khol:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Alex-Khol/${HF_SPACE_NAME}


      - name: Sync frontend to HF Space
        run: |
          rsync -av --delete \
            --exclude '.git' \
            frontend/ ${HF_SPACE_NAME}/

      - name: Commit and push to HF
        run: |
          cd ${HF_SPACE_NAME}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --quiet || git commit -m "Deploy Gradio frontend"
          git push
